src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\Column(type="integer")
     */
    private $standar;

    /**
     * @ORM\Column(type="integer")
     */
    private $promo;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     * @Assert\Valid
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Image", cascade={"persist"} , cascade={"persist","remove"} , orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Vendeur", inversedBy="produit")
     * @ORM\JoinColumn(name="vendeur_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    private $vendeur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="produit")
     * @ORM\JoinTable(name="produit_category")
     */
    private $category;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $caracteristique;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $modalite;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $modified;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getStandar(): ?int
    {
        return $this->standar;
    }

    public function setStandar(int $standar): self
    {
        $this->standar = $standar;

        return $this;
    }

    public function getPromo(): ?int
    {
        return $this->promo;
    }

    public function setPromo(int $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCaracteristique(): ?string
    {
        return $this->caracteristique;
    }

    public function setCaracteristique(?string $caracteristique): self
    {
        $this->caracteristique = $caracteristique;

        return $this;
    }

    public function getModalite(): ?string
    {
        return $this->modalite;
    }

    public function setModalite(?string $modalite): self
    {
        $this->modalite = $modalite;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getModified(): ?\DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(\DateTimeInterface $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        if($this->id != null){
            $this->modified = new \DateTime();
        }else {
            $this->created = new \DateTime();
            $this->modified = new \DateTime();
        }
        
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
        }

        return $this;
    }

    public function getVendeur(): ?Vendeur
    {
        return $this->vendeur;
    }

    public function setVendeur(?Vendeur $vendeur): self
    {
        $this->vendeur = $vendeur;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->category->contains($category)) {
            $this->category->removeElement($category);
        }

        return $this;
    }
    public function getIdentifiant()
    {
        return $this->encrypt('encrypt',$this->id);
    }
    function encrypt($action, $string) {
        $output = false;
        $encrypt_method = "AES-256-CBC";
        $secret_key = 'ffgd;jhfserfy@!$DCGGgssd';
        $secret_iv = 'ffgd;jhfserfy@@!$DCGGgssd';
        $key = hash('sha256', $secret_key);
        
        $iv = substr(hash('sha256', $secret_iv), 0, 16);
        if ( $action == 'encrypt' ) {
            $output = openssl_encrypt($string, $encrypt_method, $key, 0, $iv);
            $output = base64_encode($output);
        } else if( $action == 'decrypt' ) {
            $output = openssl_decrypt(base64_decode($string), $encrypt_method, $key, 0, $iv);
        }
        return $output;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\Vendeur;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('detail')
            ->add('standar')
            ->add('promo')
            ->add('description')
            ->add('caracteristique')
            ->add('modalite')
            ->add('image' , ImageType::class, array( 'required' => false ))
            ->add('vendeur', EntityType::class, array(
                'class' => Vendeur::class,
                'choice_label' => 'nom',
            ))
                ->add('category', EntityType::class, array(
                    'class' => Category::class,
                    'choice_label' => 'libelle',
                    'multiple' => true,
                ))
            ->add('images', CollectionType::class, array( 

             'entry_type'   => ImageType::class,
             'allow_add' => true,
             'by_reference' => false,
             'allow_delete' => true,

            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/produit")
 */
class ProduitController extends Controller
{
    /**
     * @Route("/", name="produit_index", methods="GET")
     */
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', ['produits' => $produitRepository->findAll()]);
    }

    /**
     * @Route("/new/{id}", name="produit_new", methods="GET|POST")
     */
    public function new(Request $request, $id = null ): Response
    {
        $produit = new Produit();
        $em = $this->getDoctrine()->getManager();
        if($id != null ){
            $produit = $em->getRepository(Produit::class)->find($id);
        }
       

        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($produit);
            $em->flush();
            $request->getSession()->getFlashBag()->add('ajout', 'Opération réussie avec succès !');
            return $this->redirectToRoute('produit_show' , [ 'id' => $produit->getIdentifiant()  ] );
            
            
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produit_show", methods="GET")
     */
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', ['produit' => $produit]);
    }

    /**
     * @Route("/{id}", name="produit_delete", methods="DELETE")
     */
    public function delete(Request $request, Produit $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($produit);
            $em->flush();
            $request->getSession()->getFlashBag()->add('ajout', 'L\'élément a bien été supprimé!'); 
        }

        return $this->redirectToRoute('produit_index');
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.identifiant}) }}" >

 <div aria-hidden="true" aria-labelledby="removeModalLabel" class="modal fade" id="removeModalLabel" role="dialog" tabindex="-1">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title">Confirmation de suppression</h5>
											<button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true"> ×</span></button>
										</div>
										<div class="modal-body">
                                                        <p style="text-align:center" >Voulez-vous vraiment supprimer l'element? </p>
										</div>
										<div class="modal-footer">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
											<button class="btn btn-secondary" data-dismiss="modal" type="button"> Annuler</button>
                                            <button type='submit' class="btn btn-primary" >Confirmer </button>
										</div>
									</div>
								</div>
							</div>
						</div>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Liste des produits {{ parent() }} {% endblock %}

{% block body %}
 <div class="row">
                  

                    <div class="col-12">
                        <div class="block  table-block mb-4">
                            <div class="block-heading">
                                <h5>Liste des produits </h5>
                               
                                
                            </div>


                            <div class="row">
                            <div class="pull-right"> 
                            <a href="{{ path('produit_new') }}" class="btn btn-primary">Ajouter</a>
                            <br><br>
                            </div>
                           
                            
                                <div class="table-responsive">
                                  {% for message in app.session.flashbag.get('ajout') %}
                                     
                                <div class="alert alert-success" role="alert">
                                    {{ message }}
                                </div>

                                {% endfor %}
                                    <table id="dataTable1" class="table-bordered display table table-striped" data-table="data-table">
                                        <thead>
                                       <tr>
                                        <th>Image</th>
                                        <th>Nom</th>
                                        <th>Detail</th>
                                        <th>Prix Standard</th>
                                        <th>Prix Promo</th>
                                         <th>Date d'ajout</th>
                                         <th>actions</th>
                                    </tr>
                                        </thead>
                                        <tbody>
                                        {% for produit in produits %}
                                            <tr>
                                                <td>
                                                 {% if produit.image != null %}
                                                 
                                                  <img src="{{asset(produit.image.WebPath)}}" style="height:40px;"> </td>
                                        {% endif %}
                                                </td>
                                                <td>{{ produit.nom }}</td>
                                                <td>{{ produit.detail|raw }}</td>
                                                <td>{{ produit.standar }} Euro </td>
                                                <td>{{ produit.promo }} Euro</td>
                                                <td>{{ produit.created ? produit.created|localizeddate('full', 'short') : '' }}</td>
                                                <td>
                                                     <a class="btn btn-default btn-sm" href="{{ path('produit_show' , {id:produit.identifiant} ) }}">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                                </td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td colspan="7">Aucun enregistrement</td>
                                            </tr>
                                        {% endfor %}
                                       
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
{% endblock %}

templates/produit/new.html.twig
{% extends 'admin.html.twig' %}
{% block title %}Ajouter un nouveau produit {{ parent() }} {% endblock %}
{% import _self as imgs %}
{% macro information_prototype(img) %}
<div class="form-row">
  <div class="form-group {% if img.vars.value != null %}col-md-6{% else %}col-md-10{% endif %}">
    {{ form_label(img.file, 'Image', {'label_attr': {'class': ''}}) }}
    {{ form_widget(img.file, {'attr': {'class': 'form-control' , 'placeholder' : 'Image' } }) }}
  </div>
{% if img.vars.value != null %}
  <div class="form-group col-md-4">
      <img style="width:150px" src="{{asset(img.vars.value.Webpath)}}" />
  </div>
{% endif %}
</div>
{% endmacro %}
{% block body %}
<div class="row">
  <div class="col-12">
    <div class="block  table-block mb-4">
      <div class="block-heading">
        <h5>Ajouter un nouveau produit
        </h5>
      </div>
      <div class="row"> 
        <div class="col-12" >
          {{ form_start(form) }}
          <div class="form-row">
            <div class="form-group col-md-4">
              {{ form_label(form.nom, 'Nom', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.nom, {'attr': {'class': 'form-control' , 'placeholder' : 'Nom' } }) }}
              {{ form_errors(form.nom) }}
            </div>
            <div class="form-group col-md-4">
              {{ form_label(form.standar, 'Prix Standard ', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.standar, {'attr': {'class': 'form-control' , 'placeholder' : 'Prix Standard' } }) }}
              {{ form_errors(form.standar) }}
            </div>
            <div class="form-group col-md-4">
              {{ form_label(form.promo, 'Prix Promo ', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.promo, {'attr': {'class': 'form-control' , 'placeholder' : 'Prix Promo' } }) }}
              {{ form_errors(form.promo) }}
            </div>
            <div class="form-group col-md-4">
              {{ form_label(form.vendeur, 'Vendeur ', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.vendeur, {'attr': {'class': 'form-control' , 'placeholder' : 'Vendeur' } }) }}
              {{ form_errors(form.vendeur) }}
            </div>
            <div class="form-group col-md-4">
              {{ form_label(form.category, 'Categories ', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.category, {'attr': {'class': 'form-control' , 'placeholder' : 'Categories' } }) }}
              {{ form_errors(form.category) }}
            </div>
            <div class="form-group col-md-4">
              {{ form_label(form.image.file, 'Image ', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.image.file, {'attr': {'class': 'form-control' , 'placeholder' : 'Image' } }) }}
              {{ form_errors(form.image.file) }}
            </div>
            <div class="form-group col-md-6">
              {{ form_label(form.detail, 'Détail', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.detail, {'attr': {'class': 'editor form-control ' , 'placeholder' : 'Détail' } }) }}
              {{ form_errors(form.detail) }}
            </div>
            <div class="form-group col-md-6">
              {{ form_label(form.description, 'Description', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.description, {'attr': {'class': 'editor form-control ' , 'placeholder' : 'Description' } }) }}
              {{ form_errors(form.description) }}
            </div>
            <div class="form-group col-md-6">
              {{ form_label(form.caracteristique, 'Caractéristiques', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.caracteristique, {'attr': {'class': 'editor form-control ' , 'placeholder' : 'Caractéristiques' } }) }}
              {{ form_errors(form.caracteristique) }}
            </div>
            <div class="form-group col-md-6">
              {{ form_label(form.modalite, 'Modalités de retour', {'label_attr': {'class': ''}}) }}
              {{ form_widget(form.modalite, {'attr': {'class': 'editor form-control ' , 'placeholder' : 'Modalités de retour' } }) }}
              {{ form_errors(form.modalite) }}
            </div>
          </div>
            <h5 class="panel-title">Ajouter des images 
              <span class="bt">
              </span> 
            </h5> 
            <hr>
            <div class="collection" id="parametre" data-prototype="{{ imgs.information_prototype(form.images.vars.prototype)|e }}">
              {% for image in form.images %}
              {{ imgs.information_prototype(image) }}
              {% endfor %}
              <span style="display:none;">  {{ form_widget( form.images ) }}  
              </span>
            </div>
            <div id="ajout"  >
            </div>
        </div>
        <hr>
        <div class="btn-group record_actions">
          {% if produit.id == null %}
          <a class="btn btn-inline btn-info" href="{{path('produit_index')}}">
            <i class="fa fa-chevron-circle-left">
            </i> Retour
          </a>
          {% else %}
          <a class="btn btn-inline btn-info" href="{{ path('produit_index' , {id:produit.identifiant} ) }}">
            <i class="fa fa-chevron-circle-left">
            </i> Retour
          </a>
          {% endif %}
          <button class="btn btn-primary" type="submit">Valider
          </button>
        </div>
        {{ form_end(form) }}
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function() {
    // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
    var $container = $('div#parametre');
    // On ajoute un lien pour ajouter une nouvelle catégorie
    var $addLink = $('<a href="#" id="add_category" class=""><i class="icon-plus"></i></a>');
    $('.bt').html($addLink);
    // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
    $addLink.click(function(e) {
      addCategory($container);
      e.preventDefault();
      // évite qu'un # apparaisse dans l'URL
      return false;
    }
                  );
    // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
    var index = $container.find(':input').length;
    // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
    if (index == 0) {
      addCategory($container);
      //$('#ajout').next('div').addClass('couleur_test');
    }
    else {
      // Pour chaque catégorie déjà existante, on ajoute un lien de suppression
      $container.children('div').each(function() {
        addDeleteLink($(this));
      }
                                     );
    }
    // La fonction qui ajoute un formulaire Categorie
    function addCategory($container) {
      // Dans le contenu de l'attribut « data-prototype », on remplace :
      // - le texte "__name__label__" qu'il contient par le label du champ
      // - le texte "__name__" qu'il contient par le numéro du champ
      var $prototype = $($container.attr('data-prototype').replace(/__name__label__/g, 'Période n°' + (index+1))
                         .replace(/__name__/g, index));
      //$prototype.attr('class','rows');
      // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
      addDeleteLink($prototype);
      // On ajoute le prototype modifié à la fin de la balise <div>
      $('#ajout').append($prototype);
      // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
      index++;
    }
    // La fonction qui ajoute un lien de suppression d'une catégorie
    function addDeleteLink($prototype) {
      // Création du lien
      $deleteLink = $('<div class="form-group col-md-2"><div class=""> <label class="control-label">Action</label> <br/><a href="#" class="remove"><i class="fa fa-trash" aria-hidden="true"></i></a></div></div><p>&nbsp;</p>');
      // Ajout du lien
      $prototype.append($deleteLink);
      // Ajout du listener sur le clic du lien
      $deleteLink.click(function(e) {
        $prototype.remove();
        e.preventDefault();
        // évite qu'un # apparaisse dans l'URL
        return false;
      }
                       );
    }
  }
                   );
</script>
<style>
  .bt a {
    position: relative;
    top: 4px;
    color: green;
  }
  .remove i {
    color:red
  }
</style>
{% endblock js %}

templates/produit/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Fiche Produit {{ parent() }} {% endblock %}

{% block body %}
 <div class="row">
                  

                    <div class="col-12">
                        <div class="block  table-block mb-4">
                            <div class="block-heading">
                                <h5>Fiche Produit {{produit.nom}} </h5>
                               
                                
                            </div>

                            <div class="row">
                            <div class="col-12" >
                          
                                 {% for message in app.session.flashbag.get('ajout') %}
                                     
                                <div class="alert alert-success" role="alert">
                                    {{ message }}
                                </div>

                                {% endfor %}

                             <table class="table table-hover record_properties">
                                            <tbody>
                                        {% if produit.image != null %}
                                                <tr>
                                                  <th scope="row"></th>
                                                  <td>  
                                                  <img src="{{asset(produit.image.WebPath)}}" style="height:120px;"> </td>
                                                </tr>
                                        {% endif %}
                                          
                                            <tr>
                                                <th>Nom</th>
                                                <td>{{ produit.nom }}</td>
                                            </tr>
                                            <tr>
                                                <th>Detail</th>
                                                <td>{{ produit.detail }}</td>
                                            </tr>
                                            <tr>
                                                <th>Standar</th>
                                                <td>{{ produit.standar }}</td>
                                            </tr>
                                            <tr>
                                                <th>Promo</th>
                                                <td>{{ produit.promo }}</td>
                                            </tr>
                                            <tr>
                                                <th>Description</th>
                                                <td>{{ produit.description }}</td>
                                            </tr>
                                            <tr>
                                                <th>Caracteristique</th>
                                                <td>{{ produit.caracteristique }}</td>
                                            </tr>
                                            <tr>
                                                <th>Modalite</th>
                                                <td>{{ produit.modalite }}</td>
                                            </tr>
          
                                             <tr>
                                                <th>Date d'ajout</th>
                                                <td>{{ produit.created ? produit.created|localizeddate('full', 'short') : '' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Derniere Modification</th>
                                                <td>{{ produit.modified ? produit.modified|localizeddate('full', 'short') : '' }}</td>
                                            </tr>

                                               
                                              
                                            </tbody>
                                        </table>

                                           <div class="btn-group record_actions">

                                        <a class="btn btn-inline btn-info" href="{{path('produit_index')}}">
                                            <i class="fa fa-chevron-circle-left"></i> Retour
                                        </a>

                                        <a class="btn btn-inline btn-primary" href="{{path('produit_new' , {id:produit.identifiant} )}}">
                                            Modifier <i class="fa fa-edit"></i>
                                        </a>
                                         <a href="#" class="btn btn-inline btn-danger" data-target="#removeModalLabel" data-toggle="modal" >
                                            Supprimer <i class="fa fa-trash"></i>
                                        </a>


                                    </div>
                           


                             </div>

                            </div>

                        </div>
                    </div>

                </div>

                {{ include('produit/_delete_form.html.twig') }}
                       
{% endblock %}